# Generated by Django 3.2.4 on 2022-06-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220615_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='description',
            field=models.TextField(default='Flan de Vainilla'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flan',
            name='image_url',
            field=models.URLField(default='https://th.bing.com/th/id/OIP.0RMwk_QQqQzV8Z-vc5nMkQHaDn?w=311&h=170&c=7&r=0&o=5&pid=1.7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flan',
            name='is_private',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flan',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
